Controllers/DeniedController.cs
#region Init
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CATS.Data;
using CATS.Models;
#endregion

namespace CATS.Controllers
{
	public class DeniedController : Controller
	{
		#region Declarations
		private readonly CATSDatabaseContext oCATSDatabaseContext;

		public DeniedController(CATSDatabaseContext context)
		{ oCATSDatabaseContext = context; }
		#endregion

		#region Routines
		private bool DeniedExists(int pDeniedID)
		{ return oCATSDatabaseContext.Denied.Any(oDenied => oDenied.DeniedID == pDeniedID); }
		#endregion

		#region Index
		public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.DescriptionSortParm = sortOrder == "Description" ? "Description desc" : "Description";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewData["currentFilter"] = searchString;

			var query = from oDenied in oCATSDatabaseContext.Denied
									where oDenied.DeleteFlag == false && oDenied.CompanyID == Globals.CompanyID
									select oDenied;

			if (!String.IsNullOrEmpty(searchString))
			{
				query = query.Where(select => select.Description.Contains(searchString));
			}
			switch (sortOrder)
			{
				case "Description desc":
					query = query.OrderByDescending(select => select.Description);
					break;
				default:
					query = query.OrderBy(select => select.Description);
					break;
			}

			return View(await PaginatedList<Denied>.CreateAsync(query.AsNoTracking(), page ?? 1, Globals.PageSize));
		}
		#endregion

		#region CreateEdit
		public IActionResult CreateEdit()
		{
			var oDenied = new Denied
			{
				DeniedID = 0,
				CompanyID = Globals.CompanyID,
				DeleteFlag = false
			};
			return View(oDenied);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit([Bind("DeniedID, CompanyID, Description, DeleteFlag, RecordUpdate")] Denied oDenied)
		{
			if (ModelState.IsValid)
			{
				oDenied.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Add(oDenied);
				await oCATSDatabaseContext.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(oDenied);
		}

		[HttpGet("Denied/CreateEdit/{pDeniedID:int}")]
		public async Task<IActionResult> CreateEdit(int? pDeniedID)
		{
			if (pDeniedID == null) { return NotFound(); }
			var oDenied = await oCATSDatabaseContext.Denied.SingleOrDefaultAsync(qDenied => qDenied.DeniedID == pDeniedID);
			if (oDenied == null) { return NotFound(); }
			return View(oDenied);
		}

		[HttpPost("Denied/CreateEdit/{pDeniedID:int}")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit(int pDeniedID, [Bind("DeniedID, CompanyID, Description, DeleteFlag, RecordUpdate")] Denied oDenied)
		{
			if (ModelState.IsValid)
			{
				try
				{
					oDenied.DeniedID = pDeniedID;
					oDenied.RecordUpdate = DateTime.Now;
					oCATSDatabaseContext.Update(oDenied);
					await oCATSDatabaseContext.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!DeniedExists(oDenied.DeniedID))
					{ return NotFound(); }
					else
					{ throw; }
				}
				return RedirectToAction(nameof(Index));
			}
			return View(oDenied);
		}
		#endregion

		#region Delete
		[HttpGet("Denied/Delete/{pDeniedID:int}")]
		public async Task<IActionResult> Delete(int? pDeniedID)
		{
			if (pDeniedID == null) { return NotFound(); }
			var oDenied = await oCATSDatabaseContext.Denied.SingleOrDefaultAsync(qDenied => qDenied.DeniedID == pDeniedID);
			if (oDenied == null) { return NotFound(); }
			return View(oDenied);
		}

		[HttpPost("Denied/Delete/{pDeniedID:int}"), ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? pDeniedID)
		{
			if (pDeniedID == null) { return NotFound(); }
			var oDenied = await oCATSDatabaseContext.Denied.SingleOrDefaultAsync(qDenied => qDenied.DeniedID == pDeniedID);
			if (oDenied == null) { return NotFound(); }
			try
			{
				oDenied.DeleteFlag = true;
				oDenied.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Update(oDenied);
				await oCATSDatabaseContext.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!DeniedExists(oDenied.DeniedID))
				{ return NotFound(); }
				else
				{ throw; }
			}
			return RedirectToAction(nameof(Index));
		}
		#endregion
	}
}

Controllers/EmployeeController.cs
#region Init
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CATS.Data;
using CATS.Models;
#endregion

namespace CATS.Controllers
{
	public class EmployeeController : Controller
	{
		#region Declarations
		private readonly OracleHRDatabaseContext oEmployeeContext;

		public EmployeeController(OracleHRDatabaseContext context)
		{ oEmployeeContext = context; }
		#endregion

		#region Index
		public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.LastNameSortParm = sortOrder == "LastName" ? "LastName desc" : "LastName";
			ViewBag.FirstNameSortParm = sortOrder == "FirstName" ? "FirstName desc" : "FirstName";
			ViewBag.EmployeeNumberSortParm = sortOrder == "EmployeeNumber" ? "EmployeeNumber desc" : "EmployeeNumber";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewData["currentFilter"] = searchString;

			var query = from oEmployee in oEmployeeContext.Employee
									//where oEmployee.DeleteFlag == false 
									select oEmployee;

			if (!String.IsNullOrEmpty(searchString))
			{
				query = query.Where(select => select.LastName.Contains(searchString));
			}

			switch (sortOrder)
			{
				case "LastName desc":
					query = query.OrderByDescending(select => select.LastName);
					break;
				case "FirstName":
					query = query.OrderBy(select => select.FirstName);
					break;
				case "FirstName desc":
					query = query.OrderByDescending(select => select.FirstName);
					break;
				case "EmployeeNumber":
					query = query.OrderBy(select => select.EmployeeNumber);
					break;
				case "EmployeeNumber desc":
					query = query.OrderByDescending(select => select.EmployeeNumber);
					break;
				default:
					query = query.OrderBy(select => select.LastName);
					break;
			}

			return View(await PaginatedList<Employee>.CreateAsync(query.AsNoTracking(), page ?? 1, Globals.PageSize));
		}
		#endregion

		#region "Details"
		[HttpGet("Employee/Details/{pEmployeeID:int}")]
		public async Task<IActionResult> Details(int? pEmployeeID)
		{
			if (pEmployeeID == null)
			{
				return NotFound();
			}

			var query = await oEmployeeContext.Employee
					.SingleOrDefaultAsync(select => select.EmployeeID == pEmployeeID);
			if (query == null)
			{
				return NotFound();
			}

			return View(query);
		}
		#endregion
	}
}

Controllers/GradeController.cs
#region Init
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CATS.Data;
using CATS.Models;
#endregion

namespace CATS.Controllers
{
	public class GradeController : Controller
	{
		#region Declarations
		private readonly CATSDatabaseContext oCATSDatabaseContext;

		public GradeController(CATSDatabaseContext context)
		{ oCATSDatabaseContext = context; }
		#endregion

		#region Routines
		private bool GradeExists(int pGradeID)
		{ return oCATSDatabaseContext.Grade.Any(oGrade => oGrade.GradeID == pGradeID); }
		#endregion

		#region Index
		public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.DescriptionSortParm = sortOrder == "Description" ? "Description desc" : "Description";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewData["currentFilter"] = searchString;

			var query = from oGrade in oCATSDatabaseContext.Grade
									where oGrade.DeleteFlag == false && oGrade.CompanyID == Globals.CompanyID
									select oGrade;

			if (!String.IsNullOrEmpty(searchString))
			{
				query = query.Where(select => select.Description.Contains(searchString));
			}
			switch (sortOrder)
			{
				case "Description desc":
					query = query.OrderByDescending(select => select.Description);
					break;
				default:
					query = query.OrderBy(select => select.Description);
					break;
			}

			return View(await PaginatedList<Grade>.CreateAsync(query.AsNoTracking(), page ?? 1, Globals.PageSize));
		}
		#endregion

		#region CreateEdit
		public IActionResult CreateEdit()
		{
			var oGrade = new Grade
			{
				GradeID = 0,
				CompanyID = Globals.CompanyID,
				DeleteFlag = false
			};
			return View(oGrade);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit([Bind("GradeID, CompanyID, Description, DeleteFlag, RecordUpdate")] Grade oGrade)
		{
			if (ModelState.IsValid)
			{
				oGrade.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Add(oGrade);
				await oCATSDatabaseContext.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(oGrade);
		}

		[HttpGet("Grade/CreateEdit/{pGradeID:int}")]
		public async Task<IActionResult> CreateEdit(int? pGradeID)
		{
			if (pGradeID == null) { return NotFound(); }
			var oGrade = await oCATSDatabaseContext.Grade.SingleOrDefaultAsync(qGrade => qGrade.GradeID == pGradeID);
			if (oGrade == null) { return NotFound(); }
			return View(oGrade);
		}

		[HttpPost("Grade/CreateEdit/{pGradeID:int}")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit(int pGradeID, [Bind("GradeID, CompanyID, Description, DeleteFlag, RecordUpdate")] Grade oGrade)
		{
			if (ModelState.IsValid)
			{
				try
				{
					oGrade.GradeID = pGradeID;
					oGrade.RecordUpdate = DateTime.Now;
					oCATSDatabaseContext.Update(oGrade);
					await oCATSDatabaseContext.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!GradeExists(oGrade.GradeID))
					{ return NotFound(); }
					else
					{ throw; }
				}
				return RedirectToAction(nameof(Index));
			}
			return View(oGrade);
		}
		#endregion

		#region Delete
		[HttpGet("Grade/Delete/{pGradeID:int}")]
		public async Task<IActionResult> Delete(int? pGradeID)
		{
			if (pGradeID == null) { return NotFound(); }
			var oGrade = await oCATSDatabaseContext.Grade.SingleOrDefaultAsync(qGrade => qGrade.GradeID == pGradeID);
			if (oGrade == null) { return NotFound(); }
			return View(oGrade);
		}

		[HttpPost("Grade/Delete/{pGradeID:int}"), ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? pGradeID)
		{
			if (pGradeID == null) { return NotFound(); }
			var oGrade = await oCATSDatabaseContext.Grade.SingleOrDefaultAsync(qGrade => qGrade.GradeID == pGradeID);
			if (oGrade == null) { return NotFound(); }
			try
			{
				oGrade.DeleteFlag = true;
				oGrade.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Update(oGrade);
				await oCATSDatabaseContext.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!GradeExists(oGrade.GradeID))
				{ return NotFound(); }
				else
				{ throw; }
			}
			return RedirectToAction(nameof(Index));
		}
		#endregion
	}
}

Controllers/MajorController.cs
#region Init
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CATS.Data;
using CATS.Models;
#endregion

namespace CATS.Controllers
{
	public class MajorController : Controller
	{
		#region Declarations
		private readonly CATSDatabaseContext oCATSDatabaseContext;

		public MajorController(CATSDatabaseContext context)
		{ oCATSDatabaseContext = context; }
		#endregion

		#region Routines
		private bool MajorExists(int pMajorID)
		{ return oCATSDatabaseContext.Major.Any(oMajor => oMajor.MajorID == pMajorID); }
		#endregion

		#region Index
		public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.DescriptionSortParm = sortOrder == "Description" ? "Description desc" : "Description";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewData["currentFilter"] = searchString;

			var query = from oMajor in oCATSDatabaseContext.Major
									where oMajor.DeleteFlag == false && oMajor.CompanyID == Globals.CompanyID
									select oMajor;

			if (!String.IsNullOrEmpty(searchString))
			{
				query = query.Where(select => select.Description.Contains(searchString));
			}
			switch (sortOrder)
			{
				case "Description desc":
					query = query.OrderByDescending(select => select.Description);
					break;
				default:
					query = query.OrderBy(select => select.Description);
					break;
			}

			return View(await PaginatedList<Major>.CreateAsync(query.AsNoTracking(), page ?? 1, Globals.PageSize));
		}
		#endregion

		#region CreateEdit
		public IActionResult CreateEdit()
		{
			var oMajor = new Major
			{
				MajorID = 0,
				CompanyID = Globals.CompanyID,
				DeleteFlag = false
			};
			return View(oMajor);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit([Bind("MajorID, CompanyID, Description, DeleteFlag, RecordUpdate")] Major oMajor)
		{
			if (ModelState.IsValid)
			{
				oMajor.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Add(oMajor);
				await oCATSDatabaseContext.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(oMajor);
		}

		[HttpGet("Major/CreateEdit/{pMajorID:int}")]
		public async Task<IActionResult> CreateEdit(int? pMajorID)
		{
			if (pMajorID == null) { return NotFound(); }
			var oMajor = await oCATSDatabaseContext.Major.SingleOrDefaultAsync(qMajor => qMajor.MajorID == pMajorID);
			if (oMajor == null) { return NotFound(); }
			return View(oMajor);
		}

		[HttpPost("Major/CreateEdit/{pMajorID:int}")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateEdit(int pMajorID, [Bind("MajorID, CompanyID, Description, DeleteFlag, RecordUpdate")] Major oMajor)
		{
			if (ModelState.IsValid)
			{
				try
				{
					oMajor.MajorID = pMajorID;
					oMajor.RecordUpdate = DateTime.Now;
					oCATSDatabaseContext.Update(oMajor);
					await oCATSDatabaseContext.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!MajorExists(oMajor.MajorID))
					{ return NotFound(); }
					else
					{ throw; }
				}
				return RedirectToAction(nameof(Index));
			}
			return View(oMajor);
		}
		#endregion

		#region Delete
		[HttpGet("Major/Delete/{pMajorID:int}")]
		public async Task<IActionResult> Delete(int? pMajorID)
		{
			if (pMajorID == null) { return NotFound(); }
			var oMajor = await oCATSDatabaseContext.Major.SingleOrDefaultAsync(qMajor => qMajor.MajorID == pMajorID);
			if (oMajor == null) { return NotFound(); }
			return View(oMajor);
		}

		[HttpPost("Major/Delete/{pMajorID:int}"), ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? pMajorID)
		{
			if (pMajorID == null) { return NotFound(); }
			var oMajor = await oCATSDatabaseContext.Major.SingleOrDefaultAsync(qMajor => qMajor.MajorID == pMajorID);
			if (oMajor == null) { return NotFound(); }
			try
			{
				oMajor.DeleteFlag = true;
				oMajor.RecordUpdate = DateTime.Now;
				oCATSDatabaseContext.Update(oMajor);
				await oCATSDatabaseContext.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!MajorExists(oMajor.MajorID))
				{ return NotFound(); }
				else
				{ throw; }
			}
			return RedirectToAction(nameof(Index));
		}
		#endregion
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CATS</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style01.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/site.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style01.min.css" />
  </environment>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CATS</a>
        <img src="~/Images/Education05.png" class="img-center" height="50" width="50" style="margin-top:2px; margin-bottom:2px;" />
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">TUITION REQUESTS<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a asp-area="" asp-controller="TuitionRequest" asp-action="Index">Tuition Request Processing</a></li>
              <li><a asp-area="" asp-controller="TuitionRequest" asp-action="IndexClosed">Closed Tuition Requests</a></li>
            </ul>
          </li>
          @*<li><a asp-area="" asp-controller="TuitionRequest" asp-action="Index">TUITION REQUESTS</a></li>*@
          <li><a asp-area="" asp-controller="Employee" asp-action="Index">EMPLOYEE LOOKUP</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">MAINTENANCE<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a asp-area="" asp-controller="Denied" asp-action="Index">Denied/Incomplete</a></li>
              <li><a asp-area="" asp-controller="EducationalInstitution" asp-action="Index">Educational Institution</a></li>
              <li><a asp-area="" asp-controller="FinancialAidType" asp-action="Index">Financial Aid Type</a></li>
              <li><a asp-area="" asp-controller="Grade" asp-action="Index">Grade</a></li>
              <li><a asp-area="" asp-controller="Major" asp-action="Index">Major</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">REPORTS<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a asp-area="" asp-controller="Denied" asp-action="Index">Denied/Incomplete</a></li>
              <li><a asp-area="" asp-controller="EducationalInstitution" asp-action="Index">Educational Institution</a></li>
              <li><a asp-area="" asp-controller="FinancialAidType" asp-action="Index">Financial Aid Type</a></li>
              <li><a asp-area="" asp-controller="Grade" asp-action="Index">Grade</a></li>
              <li><a asp-area="" asp-controller="Major" asp-action="Index">Major</a></li>
            </ul>
          </li>
          <li><a asp-area="" asp-controller="Home" asp-action="About">ABOUT</a></li>
          <li><a asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a></li>
        </ul>
        <label class="navbar-text navbar-right">@ViewBag.UserFirstName</label>
      </div>
    </div>
  </nav>
  <div class="container body-content">
    @RenderBody()
    <hr />
  </div>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.min.js"></script>
  </environment>

  @RenderSection("Scripts", required: false)
  </body>
</html>