Controllers/TuitionRequestController.cs
#region Init
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CATS.Data;
using CATS.Models;
using System.Collections.Generic;
using System.Globalization;
#endregion

namespace CATS.Controllers
{
	public class TuitionRequestController : Controller
	{
		#region Declarations
		private CATSDatabaseContext oCATSDatabaseContext;
		//private UnityInterfacesDatabaseContext oUnityInterfacesDatabaseContext;
		private OracleHRDatabaseContext oOracleHRDatabaseContext;

		public TuitionRequestController(
					[FromServices] CATSDatabaseContext pCATSDatabaseContext,
					//[FromServices] UnityInterfacesDatabaseContext pUnityInterfacesDatabaseContext,
					[FromServices] OracleHRDatabaseContext pOracleHRDatabaseContext)
		{
			oCATSDatabaseContext = pCATSDatabaseContext;
			//oUnityInterfacesDatabaseContext = pUnityInterfacesDatabaseContext;
			oOracleHRDatabaseContext = pOracleHRDatabaseContext;
		}
		#endregion

		#region Routines
		private bool TuitionRequestExists(int pTuitionRequestID)
		{ return oCATSDatabaseContext.TuitionRequests.Any(oTuitionRequest => oTuitionRequest.TuitionRequestID == pTuitionRequestID); }

		private void GetPaymentOptionList()
		{
			List<PaymentOption> oPaymentOptionList = new List<PaymentOption>();
			oPaymentOptionList = (from oPaymentOption in oCATSDatabaseContext.PaymentOption
														where oPaymentOption.DeleteFlag == false && oPaymentOption.CompanyID == Globals.CompanyID
														orderby oPaymentOption.Description
														select oPaymentOption).ToList();
			//oPaymentOptionList.Insert(0, new PaymentOption { PaymentOptionID = 0, Description = "Select" });
			ViewBag.ListOfPaymentOption = oPaymentOptionList;
		}

		private void GetFinancialAidTypeList()
		{
			List<FinancialAidType> oFinancialAidTypeList = new List<FinancialAidType>();
			oFinancialAidTypeList = (from oFinancialAidType in oCATSDatabaseContext.FinancialAidType
															 where oFinancialAidType.DeleteFlag == false && oFinancialAidType.CompanyID == Globals.CompanyID
															 orderby oFinancialAidType.Description
														select oFinancialAidType).ToList();
			oFinancialAidTypeList.Insert(0, new FinancialAidType { FinancialAidTypeID = 0, Description = "Select" });
			ViewBag.ListOfFinancialAidType = oFinancialAidTypeList;
		}

		private void GetEducationalInstitutionList()
		{
			List<EducationalInstitution> oEducationalInstitutionList = new List<EducationalInstitution>();
			oEducationalInstitutionList = (from oEducationalInstitution in oCATSDatabaseContext.EducationalInstitution
																		 where oEducationalInstitution.DeleteFlag == false && oEducationalInstitution.CompanyID == Globals.CompanyID
																		 orderby oEducationalInstitution.Description
															 select oEducationalInstitution).ToList();
			oEducationalInstitutionList.Insert(0, new EducationalInstitution { EducationalInstitutionID = 0, Description = "Select" });
			ViewBag.ListOfEducationalInstitution = oEducationalInstitutionList;
		}

		private void GetEducationalProgramList()
		{
			List<EducationalProgram> oEducationalProgramList = new List<EducationalProgram>();
			oEducationalProgramList = (from oEducationalProgram in oCATSDatabaseContext.EducationalProgram
											where oEducationalProgram.DeleteFlag == false && oEducationalProgram.CompanyID == Globals.CompanyID
											orderby oEducationalProgram.SortOrder
															 select oEducationalProgram).ToList();
			oEducationalProgramList.Insert(0, new EducationalProgram { EducationalProgramID = 0, Description = "Select" });
			ViewBag.ListOfEducationalProgram = oEducationalProgramList;
		}

		private void GetMajorList()
		{
			List<Major> oMajorList = new List<Major>();
			oMajorList = (from oMajor in oCATSDatabaseContext.Major
										where oMajor.DeleteFlag == false && oMajor.CompanyID == Globals.CompanyID
										orderby oMajor.Description
															 select oMajor).ToList();
			oMajorList.Insert(0, new Major { MajorID = 0, Description = "Select" });
			ViewBag.ListOfMajor = oMajorList;
		}

		private void GetStatusList()
		{
			List<Status> oStatusList = new List<Status>();
			oStatusList = (from oStatus in oCATSDatabaseContext.Status
										 where oStatus.DeleteFlag == false && oStatus.CompanyID == Globals.CompanyID
										 orderby oStatus.SortOrder
										 select oStatus).ToList();
			//oStatusList.Insert(0, new Status { StatusID = 0, Description = "Select" });
			ViewBag.ListOfStatus = oStatusList;
		}

		private void GetGradeList()
		{
			List<Grade> oGradeList = new List<Grade>();
			oGradeList = (from oGrade in oCATSDatabaseContext.Grade
										 where oGrade.DeleteFlag == false && oGrade.CompanyID == Globals.CompanyID
										 orderby oGrade.Description
										 select oGrade).ToList();
			oGradeList.Insert(0, new Grade { GradeID = 0, Description = "Select" });
			ViewBag.ListOfGrade = oGradeList;
		}

		private void GetDeniedList()
		{
			List<Denied> oDeniedList = new List<Denied>();
			oDeniedList = (from oDenied in oCATSDatabaseContext.Denied
										 where oDenied.DeleteFlag == false && oDenied.CompanyID == Globals.CompanyID
										 orderby oDenied.Description
										select oDenied).ToList();
			oDeniedList.Insert(0, new Denied { DeniedID = 0, Description = "Select" });
			ViewBag.ListOfDenied = oDeniedList;
		}

		//private string GetAccountNumber(string pCostCenter, int pEducationalProgramID)
		//{
		//	string sAccountNumber;
		//	if (pCostCenter.Length < 9) { return string.Empty; }
		//	string sPrefix = pCostCenter.Substring(0, 3);
		//	string sDepartmentNumber = pCostCenter.Substring(pCostCenter.Length - 6, 6);

		//	switch (sPrefix)
		//	{
		//		case "150":
		//			if (pEducationalProgramID == 1 || pEducationalProgramID == 2)
		//			{
		//				sAccountNumber = "1506-854000-25500";
		//			}
		//			else
		//			{
		//				sAccountNumber = "1506-854000-20500";
		//			}
		//			break;
		//		case "550":
		//			if (pEducationalProgramID == 1 || pEducationalProgramID == 2)
		//			{
		//				sAccountNumber = "5506-" + sDepartmentNumber + "-72001";
		//			}
		//			else
		//			{
		//				sAccountNumber = "5506-" + sDepartmentNumber + "-72000";
		//			}
		//			break;
		//		case "120":
		//			if (pEducationalProgramID == 1 || pEducationalProgramID == 2)
		//			{
		//				sAccountNumber = "1206-854000-25500";
		//			}
		//			else
		//			{
		//				sAccountNumber = "1206-854000-20500";
		//			}
		//			break;
		//		case "200":
		//			if (pEducationalProgramID == 1 || pEducationalProgramID == 2)
		//			{
		//				sAccountNumber = "2006-854000-25500";
		//			}
		//			else
		//			{
		//				sAccountNumber = "2006-854000-20500";
		//			}
		//			break;
		//		case "600":
		//			sAccountNumber = "6006-" + sDepartmentNumber + "-20500";
		//			break;
		//		case "110":
		//			if (sDepartmentNumber.Substring(1, 3) == "108")
		//			{
		//				sAccountNumber = "1101-108000-70000";
		//			}
		//			else
		//			{
		//				if (pEducationalProgramID == 1 || pEducationalProgramID == 2)
		//				{
		//					sAccountNumber = "1106-854000-25500";
		//				}
		//				else
		//				{
		//					sAccountNumber = "1106-854000-20500";
		//				}
		//			}
		//			break;
		//		default:
		//			sAccountNumber = string.Empty;
		//			break;
		//	}
		//	return sAccountNumber;
		//}

		//private double GetReimbursementPercent(int pEducationalProgramID, string sEmployeeStatus)
		//{
		//	if (pEducationalProgramID == 3 || pEducationalProgramID == 5)
		//	{
		//		return 1;
		//	}
		//	switch (sEmployeeStatus)
		//	{
		//		case "01":
		//			return 1;
		//		case "25":
		//			return .5;
		//		default:
		//			return 0;
		//	}
		//}

		private double GetReimbursementPercent(int pEducationalProgramID, string pEmploymentCategoryCode)
		{
			if (pEducationalProgramID == 3 || pEducationalProgramID == 5)
			{
				return 1;
			}
			if (pEmploymentCategoryCode == null)
			{
				return 0;
			}
			switch (pEmploymentCategoryCode.ToLower())
			{
				case "fr":
					return 1;
				case "pr":
					return .5;
				default:
					return 0;
			}
		}

		//private double GetMaximumReimbursementAmount(string pPositionNumber, string sEmployeeStatus) 
		//{
		//	if (sEmployeeStatus != "01" && sEmployeeStatus != "25")
		//	{
		//		return 0;
		//	}
		//	Position oPosition = oCATSDatabaseContext.Position.SingleOrDefault(Position => Position.PositionNumber == pPositionNumber && Position.DeleteFlag == false);
		//	if (oPosition != null)
		//	{
		//			return 8000;
		//	}
		//	else
		//	{
		//		return 4000;
		//	}
		//}

		private double GetMaximumReimbursementAmount(string pJobCode, string sEmployeeStatus)
		{
			if (sEmployeeStatus.ToUpper() != "ACTIVE_PROCESS")
			{
				return 0;
			}
			JobCodeIR oJobCodeIR = oCATSDatabaseContext.JobCodeIR.SingleOrDefault(JobCodeIR => JobCodeIR.JobCode == pJobCode && JobCodeIR.DeleteFlag == false);
			if (oJobCodeIR != null)
			{
				return 8000;
			}
			else
			{
				return 4000;
			}
		}

		private string SetAccountNumber(string sCompanyID, string sDepartmentNumber)
		{
			if (sCompanyID.Trim() == "4110" || sCompanyID.Trim() == "9040")
			{
				return sCompanyID.Trim();
			}
			if (sCompanyID.Trim() == "4400")
			{
				return sCompanyID.Trim() + " " + sDepartmentNumber.Trim() + " 79110";
			}
			return sCompanyID.Trim() + " " + sDepartmentNumber.Trim() + " 62070";
		}

		private double GetYTDTuitionReceived(Int64 pEmployeeNumber, int pTuitionRequestID, string pJobCode, DateTime pCourseStartDate, int pEducationalProgramID)
		{
			double dReturnAmount = 0;
			List<TuitionRequest> oList = new List<TuitionRequest>();

Views/TuitionRequest/Delete.cshtml
@model CATS.Models.TuitionRequest
@{var sTitle = "Tuition Request";}
<div class="container-fluid">
  <h2 class="offseth2">Delete @sTitle</h2>
  <form asp-action="Delete">
    <hr class="style02" />
    <div class="row" style="font-weight:bold;">
      <div class="col-md-4">
        @Html.DisplayFor(Model => Model.Comment)
      </div>
    </div>
    <h5>Are you sure you want to delete this @sTitle?</h5>

    <div class="form-group">
      <hr class="style02" />
    </div>
    <div class="clear01" />

    <div class="form-group">
      <input type="submit" value="Delete" class="btn btn-default" /> | <a asp-action="Index">Back to List</a>
    </div>

    <input type="hidden" asp-for="TuitionRequestID" />
    <input type="hidden" asp-for="CompanyID" />
    <input type="hidden" asp-for="Comment" />
    <input type="hidden" asp-for="DeleteFlag" />
    <input type="hidden" asp-for="RecordUpdate" />
  </form>
</div>

Views/TuitionRequest/EmployeeDetails.cshtml
@model CATS.Models.Employee
@*@{
  ViewData["Title"] = "Tuition Request Processing: Employee Details";
}*@
<h2 class="offseth2">Tuition Request Processing: Employee Details</h2>

  <hr class="style03" />
  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(Model => Model.EmployeeNumber):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(Model => Model.EmployeeNumber)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      Employee Name:
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.LastName), @Html.DisplayFor(model => model.FirstName)
    </div>
  </div>

  @*<div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.SocialSecurityNumber):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.SocialSecurityNumber)
    </div>
  </div>*@

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.DateOfHire):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.DateOfHire)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.EmployeeStatus):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.EmployeeStatus)-@Html.DisplayFor(model => model.StatusDescription)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.EmploymentCategoryCode)-@Html.DisplayNameFor(model => model.EmploymentCategoryName):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.EmploymentCategoryCode)-@Html.DisplayFor(model => model.EmploymentCategoryName)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.Position):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.PositionNumber)-@Html.DisplayFor(model => model.Position)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.JobCode)-@Html.DisplayNameFor(model => model.JobName):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.JobCode)-@Html.DisplayFor(model => model.JobName)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.UnionCode):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.UnionCode)
    </div>
  </div>


  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.CostCenter):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.CostCenter)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.Entity):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.Entity)
    </div>
  </div>

  <div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.HomePhone):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.HomePhone)
    </div>
  </div>

  @*<div class="row">
      <div class="col-md-3" style="text-align:right; font-weight:bold">
        @Html.DisplayNameFor(model => model.YTDTuitionReceived):
      </div>
      <div class="col-md-4">
        @Html.DisplayFor(model => model.YTDTuitionReceived)
      </div>
    </div>*@

  @*<div class="row" style="margin-bottom:5px;">
    <div class="col-md-3" style="text-align:right; font-weight:bold;">
      @Html.DisplayNameFor(model => model.MaximumReimbursement):
    </div>
    <div class="col-md-4">
      @Html.DisplayFor(model => model.MaximumReimbursement)
    </div>
  </div>*@

  <hr class="style03" />
  <div class="clear01" />
  <div>
    <a asp-controller="TuitionRequest" asp-action="CreateEdit" asp-route-pEmployeeID="@Model.EmployeeID" asp-route-pNewFlag="0">Select</a> |
    <a asp-controller="TuitionRequest" asp-action="EmployeeIndex">Back to List</a>
  </div>

Views/TuitionRequest/EmployeeIndex.cshtml
@model PaginatedList<CATS.Models.Employee>
@*@{  ViewData["Title"] = "EmployeeIndex"; }*@

<h2 class="offseth2">Tuition Request Processing: Employee Selection</h2>

<form asp-controller="TuitionRequest" asp-action="EmployeeIndex" method="get">
  <div class="row">
    <div class="col-lg-12">
      <div class="form-group no-color">
        <p>
          Find by Last Name: <input type="text" class="form-control findby01" name="SearchString" value="@ViewBag.CurrentFilter" />
          <input type="submit" value="Search" class="btn btn-default" /> |
          <a asp-controller="TuitionRequest" asp-action="EmployeeIndex">Back to Full List</a>
        </p>
      </div>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>
          @Html.ActionLink("Last Name", "EmployeeIndex", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("First Name", "EmployeeIndex", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Employee Number", "EmployeeIndex", new { sortOrder = ViewBag.EmployeeNumberSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
        <tr>
          <td>
            @Html.DisplayFor(modelItem => item.LastName)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.FirstName)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.EmployeeNumber)
          </td>
          <td>
            <a asp-controller="TuitionRequest" asp-action="EmployeeDetails" asp-route-id="@item.EmployeeID">Details</a> |
            <a asp-controller="TuitionRequest" asp-action="CreateEdit" asp-route-pEmployeeID="@item.EmployeeID" asp-route-pNewFlag="0">Select</a>
          </td>
        </tr>
      }
    </tbody>
  </table>

  @{
    var bPreviousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var bNextDisabled = !Model.HasNextPage ? "disabled" : "";
  }

  <a asp-action="EmployeeIndex"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex - 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bPreviousDisabled">
    Previous
  </a>
  <text class="pagenumber01">Page @(Model.TotalPages < Model.PageIndex ? 0 : Model.PageIndex) of @Model.TotalPages</text>
  <a asp-action="EmployeeIndex"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex + 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bNextDisabled">
    Next
  </a>
</form>

Views/TuitionRequest/Index.cshtml
@model PaginatedList<CATS.Models.TuitionRequestDisplay>
@{ ViewData["Title"] = "Index"; }

<h2 class="offseth2">Tuition Request Processing</h2>

<form asp-action="Index" method="get">
  <div class="row">
    <div class="col-lg-12">
      <div class="form-group no-color">
        <p>
          Find by Last Name: <input type="text" class="form-control findby01" name="SearchString" value="@ViewBag.CurrentFilter" />
          <input type="submit" value="Search" class="btn btn-default" /> |
          <a asp-action="Index">Back to Full List</a>
        </p>
      </div>
    </div>
  </div>

  <p><a asp-controller="TuitionRequest" asp-action="EmployeeIndex">Create New</a></p>

  <table class="table">
    <thead>
      <tr>
        <th>
          @Html.ActionLink("Request Number", "Index", new { sortOrder = ViewBag.RequestNumberSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Employee Number", "Index", new { sortOrder = ViewBag.EmployeeNumberSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusDescriptionSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.RequestNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.StatusDescription)
        </td>
        <td>
          <a asp-action="CreateEdit" asp-route-id="@item.TuitionRequestID">Edit</a> | <a asp-action="Delete" asp-route-id="@item.TuitionRequestID">Delete</a>
        </td>
      </tr>
      }
    </tbody>
  </table>

  @{
    var bPreviousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var bNextDisabled = !Model.HasNextPage ? "disabled" : "";
  }

  <a asp-action="Index"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex - 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bPreviousDisabled">
    Previous
  </a>
  <text class="pagenumber01">Page @(Model.TotalPages < Model.PageIndex ? 0 : Model.PageIndex) of @Model.TotalPages</text>
  <a asp-action="Index"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex + 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bNextDisabled">
    Next
  </a>
</form>

Views/TuitionRequest/IndexClosed.cshtml
@model PaginatedList<CATS.Models.TuitionRequestDisplay>
@{ ViewData["Title"] = "IndexClosed"; }

<h2 class="offseth2">Closed Tuition Requests</h2>

<form asp-action="IndexClosed" method="get">
  <div class="row">
    <div class="col-lg-12">
      <div class="form-group no-color">
        <p>
          Find by Last Name: <input type="text" class="form-control findby01" name="SearchString" value="@ViewBag.CurrentFilter" />
          <input type="submit" value="Search" class="btn btn-default" /> |
        </p>
      </div>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>
          @Html.ActionLink("Request Number", "IndexClosed", new { sortOrder = ViewBag.RequestNumberSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Last Name", "IndexClosed", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("First Name", "IndexClosed", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Employee Number", "IndexClosed", new { sortOrder = ViewBag.EmployeeNumberSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
          @Html.ActionLink("Status", "IndexClosed", new { sortOrder = ViewBag.StatusDescriptionSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.RequestNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.StatusDescription)
        </td>
        <td>
          <a asp-controller="TuitionRequest" asp-action="Details" asp-route-id="@item.TuitionRequestID">Details</a>
        </td>
      </tr>
      }
    </tbody>
  </table>

  @{
    var bPreviousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var bNextDisabled = !Model.HasNextPage ? "disabled" : "";
  }

  <a asp-action="IndexClosed"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex - 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bPreviousDisabled">
    Previous
  </a>
  <text class="pagenumber01">Page @(Model.TotalPages < Model.PageIndex ? 0 : Model.PageIndex) of @Model.TotalPages</text>
  <a asp-action="IndexClosed"
     asp-route-sortOrder="@ViewBag.currentSort"
     asp-route-page="@(Model.PageIndex + 1)"
     asp-route-currentFilter="@ViewBag.currentFilter"
     class="btn btn-default @bNextDisabled">
    Next
  </a>
</form>